modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
credits="UI sound effects: Nathan Gibson — Universal UI/Menu Soundpack (CC BY 4.0)"
description='''${mod_description}'''
displayTest="MATCH_VERSION"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[21.1,21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="curios"
type="optional"
versionRange="[9,10)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="beyonddimensions"
type="optional"
versionRange="[0.3.0,)"
ordering="AFTER"
side="BOTH"
