modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
credits="UI sound effects: Nathan Gibson — Universal UI/Menu Soundpack (CC BY 4.0)"
description='''${mod_description}'''
displayTest="MATCH_VERSION"

[[mixins]]
config="rpgmenuframework.ftbquests.mixins.json"

[[mixins]]
config="rpgmenuframework.embedded_map.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[21.1,21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="curios"
type="optional"
versionRange="[9,10)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="moreoffhandslots"
type="optional"
versionRange="[21.1,22)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="beyonddimensions"
type="optional"
versionRange="[0.3.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="xaeroworldmap"
type="optional"
versionRange="[1.40.2,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="journeymap"
type="optional"
versionRange="[0,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="epicfight"
type="optional"
versionRange="[21.12.1,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="epicskills"
type="optional"
versionRange="[21.3,)"
ordering="AFTER"
side="BOTH"
